services:
  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es1c-users:latest
    expose:
      - "3000"
    networks:
      - monitor-net

  auth:
    build: ./auth
    container_name: auth
    image: ghcr.io/arquisoft/yovi_es1c-auth:latest
    environment:
      - JWT_SECRET=${JWT_SECRET}"
      - AUTH_DB_PATH=${AUTH_DB_PATH:-/app/data/auth.db}
    networks:
      - monitor-net
    volumes:
      - ./data:/app/data
  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=/api/users
        - VITE_GAMEY_API_URL=/api/gamey
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es1c-webapp:latest
    expose:
      - "80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es1c-gamey:latest
    expose:
      - "4000"
    networks:
      - monitor-net
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
      - users
      - gamey
    networks:
      - monitor-net
    restart: unless-stopped

  gameservice:
    build: ./gameservice
    container_name: gameservice
    image: ghcr.io/arquisoft/yovi_es1c-gameservice:latest
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - GAME_DB_PATH=/app/data/game.db
    volumes:
      - ./gameservice/data:/app/data
    expose:
      - "3002"
    ports:
    - "3002:3002"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
